### ISSUE TITLE
Please update to V2 api

### ISSUE THREAD

**Issue by ugjka** [bsorahan/certbot-dns-vultr#1]
![Screenshot_20230421_180216](https://user-images.githubusercontent.com/13318673/233669741-3b736e68-0d27-4aa4-854c-521451340005.png)

**Comment by mtietje** [comment]
I'm having issues with this too in a new install of nginxproxymanager. 

> Error fetching DNS domains list: 503 - Sorry, all newly created accounts are forbidden from using API v1, all other accounts are able to use this deprecated API until June 30, 2023 at which point Vultr API v1 will be sunset. Please use API v2.

**Comment by bsorahan** [comment]
This is sue to old versions of dn-lexicon. dns-lexicon>=3.6.0 are using Vultr API v2. So this should be resolved in v0.2.0
